import { defineConfig, devices } from "@playwright/test";

/**
 * E2E tests run against the local dev server + local Supabase stack.
 * Before running: ensure `scripts/dev-local.sh` is running in another terminal.
 *
 * Auth storage states are generated by the global setup on first run.
 * They are .gitignored (contain session tokens).
 */
export default defineConfig({
  testDir: "./e2e/tests",
  globalSetup: "./e2e/global-setup.ts",
  outputDir: "./e2e/results",
  fullyParallel: false,
  retries: process.env.CI ? 2 : 0,
  reporter: "list",
  use: {
    baseURL: "http://localhost:5173",
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "admin",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "e2e/fixtures/admin-state.json",
      },
    },
    {
      name: "technician",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "e2e/fixtures/technician-state.json",
      },
    },
  ],
});
